escamboapp/config/routes.rb
Rails.application.routes.draw do

  get 'backoffice', to: 'backoffice/dashboard#index'
  namespace :backoffice do
  resources :categories, except: [:show, :destroy]
  resources :admins, except: [:show]
  get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
  get 'home', to: 'home#index'
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members
  root 'site/home#index'

end

escamboapp/app/models/ad.rb
class Ad < ActiveRecord::Base
  belongs_to :category
  belongs_to :member
end

escamboapp/app/models/admin.rb
class Admin < ActiveRecord::Base
  enum role: [:full_access, :restricted_access]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def role_br
    if self.role == 'full_access'
      'Acesso Completo'
    else
      'Acesso Restrito'
    end
  end
end

escamboapp/app/models/category.rb
class Category < ActiveRecord::Base
  validates_presence_of :description
end

escamboapp/app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

escamboapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller? && resource_name == :admin
      "backoffice_devise"
    else
      "application"
    end
  end
end

escamboapp/app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]
  def index
    @admins = Admin.all
  end
  def new
    @admin = Admin.new
  end
  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to backoffice_admins_path, notice: "O Administrador (#{@admin.email}) foi cadastrado com sucesso!"
    else
      render :new
    end
  end
  def edit
  end
  def update
    passwd = params[:admin][:password]
    passwd_confirmation = params[:admin][:password_confirmation]
    if passwd.blank? && passwd_confirmation.blank?
      params[:admin].delete :password
      params[:admin].delete :password_confirmation
    end
    if @admin.update(params_admin)
      redirect_to backoffice_admins_path, notice: "O Administrador (#{@admin.email}) foi atualizado com sucesso!"
    else
      render :edit
    end
  end

  def destroy
    admin_email = @admin.email
    if @admin.destroy
      redirect_to backoffice_admins_path, notice: "O Administrador (#{admin_email}) foi excluido com sucesso!"
    else
      render :index
    end
  end

  private
  def set_admin
    @admin = Admin.find(params[:id])
  end
  def params_admin
    params.require(:admin).permit(:email, :name, :password, :password_confirmation)
  end
end

escamboapp/app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :set_category, only: [:edit, :update]
  def index
    @categories = Category.all
  end
  def new
    @category = Category.new
  end
  def create
    @category = CategoryService.create(params_category)
    unless @category.errors.any?
      redirect_to backoffice_categories_path, notice: "A categoria (#{@category.description}) foi cadastrada com sucesso!"
    else
      render :new
    end
  end
  def edit
  end
  def update
    if @category.update(params_category)
      redirect_to backoffice_categories_path, notice: "A categoria (#{@category.description}) foi atualizada com sucesso!"
    else
      render :edit
    end
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end
  def params_category
    params.require(:category).permit(:description)
  end
end

escamboapp/app/controllers/backoffice/categories_controller/category_service.rb
class Backoffice::CategoriesController::CategoryService
  attr_accessor :category

  def self.create(params_category)
    @category = Category.new(params_category)

    if @category.valid?
      @category.save!
    end

    @category
  end
end

escamboapp/app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController

  def index
  end
end

escamboapp/app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout "backoffice"
end

escamboapp/app/controllers/site/home_controller.rb
class Site::HomeController < ApplicationController
  layout "site"
  def index
    @categories = Category.all
  end
end

escamboapp/app/helpers/application_helper.rb
module ApplicationHelper
end

escamboapp/app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
end

escamboapp/app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

escamboapp/app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

escamboapp/app/helpers/site/home_helper.rb
module Site::HomeHelper
end

escamboapp/app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

escamboapp/app/views/backoffice/admins/shared/_form.html.erb
<h1 class="page-header">Administradores</h1>
<% if @admin.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <ul>
            <%= @admin.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>
  <div class="panel panel-default">
    <div class="panel-heading">
        <%= action %>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="col-lg-6">
            <%= form_for([:backoffice,@admin]) do |f| %>
                <div class="form-group">
                    <label>E-mail</label>
                    <%= f.text_field :email, class:"form-control", placeholder:"E-mail" %>
                </div>
                <div class="form-group">
                    <label>Nome</label>
                    <%= f.text_field :name, class:"form-control", placeholder:"Nome do Administrador" %>
                </div>
                <div class="form-group">
                    <label>Senha</label>
                    <%= f.password_field :password, class:"form-control", placeholder:"Senha" %>
                </div>
                <div class="form-group">
                    <label>Confirmação da Senha</label>
                    <%= f.password_field :password_confirmation, class:"form-control", placeholder:"Confirmação da Senha" %>
                </div>

                <button type="submit" class="btn btn-default">Salvar</button>
            <% end %>
        </div>
    </div>
    <!-- /.panel-body -->
  </div>

escamboapp/app/views/backoffice/categories/edit.html.erb
<%= render partial: "backoffice/categories/shared/form", locals: {action: "Editando Categoria"} %>

escamboapp/app/views/backoffice/categories/index.html.erb
<h1 class="page-header">Categorias</h1>
  <div class="panel panel-default">
    <div class="panel-heading">
        Listando Categorias
        <%= link_to new_backoffice_category_path, class: "btn btn-success btn-circle pull-right", style:"margin-top: -5px;" do %>
            <i class="fa fa-plus"></i>
        <% end %>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Descrição</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <% @categories.each do |category| %>
                      <tr>
                          <td><%= category.id %></td>
                          <td><%= category.description %></td>
                          <td style="width: 100px;">
                            <%= link_to edit_backoffice_category_path(category.id), class: "btn btn-primary btn-circle" do %>
                                <i class="fa fa-edit"></i></button>
                            <% end %>
                            <button type="button" class="btn btn-danger btn-circle" disabled="disabled"><i class="fa fa-minus"></i></button>
                          </td>
                      </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>
    <!-- /.panel-body -->
  </div>

escamboapp/app/views/backoffice/categories/new.html.erb
<%= render partial: "backoffice/categories/shared/form", locals: {action: "Nova Categoria"} %>

escamboapp/app/views/backoffice/categories/shared/_form.html.erb
<h1 class="page-header">Categorias</h1>
<% if @category.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <ul>
            <%= @category.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>
  <div class="panel panel-default">
    <div class="panel-heading">
        <%= action %>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="col-lg-6">
            <%= form_for([:backoffice,@category]) do |f| %>
                <div class="form-group">
                    <label>Descrição</label>
                    <%= f.text_field :description, class:"form-control", placeholder:"Ex: Animais/Pet" %>
                </div>

                <button type="submit" class="btn btn-default">Salvar</button>
            <% end %>
        </div>
    </div>
    <!-- /.panel-body -->
  </div>

escamboapp/app/views/backoffice/dashboard/index.html.erb
<h1 class="page-header">Dashboard</h1>

escamboapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Escamboapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

escamboapp/app/views/layouts/backoffice.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

      <title>Backoffice - Escamboapp</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= stylesheet_link_tag    'backoffice', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'backoffice', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
</head>
<body>

    <div id="wrapper">
      <%= render "layouts/backoffice_shared/navigation" %>
      <!-- Page Content -->
      <div id="page-wrapper">
          <div class="container-fluid">
              <div class="row">
                  <div class="col-lg-12">
                      <%= yield %>
                  </div>
            <!-- /.col-lg-12 -->
              </div>
              <!-- /.row -->
          </div>
          <!-- /.container-fluid -->
      </div>
      <!-- /#page-wrapper -->
    </div>

<% if notice %>
  <script>$.notify("<%= notice %>", "success")</script>
<% end %>

</body>
</html>

escamboapp/app/views/layouts/backoffice_devise.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

      <title>Backoffice - Escamboapp</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= stylesheet_link_tag    'backoffice', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'backoffice', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>

</html>

escamboapp/app/views/layouts/backoffice_shared/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "Backoffice - Escamboapp", backoffice_path, class: "navbar-brand" %>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li><%= current_admin.email %></li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>

                    <ul class="dropdown-menu dropdown-user">
                        <li><%= link_to destroy_admin_session_path, method: :delete, data: {confirm: "Tem certeza que deseja Sair? "} do %>
                            <i class='fa fa-sign-out fa-fw'></i> Logout
                        <% end %>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                        <%= link_to backoffice_path do%>
                            <i class="fa fa-dashboard fa-fw"></i> Dashboard
                        <% end %>
                        </li>
                        <li>
                            <%= link_to backoffice_categories_path do%>
                                <i class="fa fa-th-list fa-fw"></i> Categorias
                            <% end %>
                        </li>
                        <li>
                            <%= link_to   backoffice_admins_path do%>
                                <i class="fa fa-users fa-fw"></i> Administradores
                            <% end %>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

escamboapp/app/views/layouts/site.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>EscamboApp</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'site', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'site', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
<%= render partial: "layouts/site_shared/navigation" %>
<%= yield %>
<%= render partial: "layouts/site_shared/footer" %>


</body>

</html>

escamboapp/app/views/layouts/site_shared/_footer.html.erb
  <!-- /.container -->

    <div class="container">

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

escamboapp/app/views/layouts/site_shared/_navigation.html.erb
<!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Start Bootstrap</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Services</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

escamboapp/app/views/site/home/index.html.erb
    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <div class="col-md-3">
                <p class="lead">Categorias</p>
                <div class="list-group">
                    <% @categories.each do |category| %>
                        <a href="#" class="list-group-item"><%= category.description %></a>
                    <% end %>
                </div>
            </div>

            <div class="col-md-9">

                <div class="row carousel-holder">

                    <div class="col-md-12">
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner">
                                <div class="item active">
                                    <img class="slide-image" src="http://placehold.it/800x300" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="http://placehold.it/800x300" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="http://placehold.it/800x300" alt="">
                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    </div>

                </div>

                <div class="row">

                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <img src="http://placehold.it/320x150" alt="">
                            <div class="caption">
                                <h4 class="pull-right">$24.99</h4>
                                <h4><a href="#">First Product</a>
                                </h4>
                                <p>See more snippets like this online store item at <a target="_blank" href="http://www.bootsnipp.com">Bootsnipp - http://bootsnipp.com</a>.</p>
                            </div>
                            <div class="ratings">
                                <p class="pull-right">15 reviews</p>
                                <p>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <img src="http://placehold.it/320x150" alt="">
                            <div class="caption">
                                <h4 class="pull-right">$64.99</h4>
                                <h4><a href="#">Second Product</a>
                                </h4>
                                <p>This is a short description. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                            </div>
                            <div class="ratings">
                                <p class="pull-right">12 reviews</p>
                                <p>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star-empty"></span>
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <img src="http://placehold.it/320x150" alt="">
                            <div class="caption">
                                <h4 class="pull-right">$74.99</h4>
                                <h4><a href="#">Third Product</a>
                                </h4>
                                <p>This is a short description. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                            </div>
                            <div class="ratings">
                                <p class="pull-right">31 reviews</p>
                                <p>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star-empty"></span>
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <img src="http://placehold.it/320x150" alt="">
                            <div class="caption">
                                <h4 class="pull-right">$84.99</h4>
                                <h4><a href="#">Fourth Product</a>
                                </h4>
                                <p>This is a short description. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                            </div>
                            <div class="ratings">
                                <p class="pull-right">6 reviews</p>
                                <p>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star-empty"></span>
                                    <span class="glyphicon glyphicon-star-empty"></span>
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <img src="http://placehold.it/320x150" alt="">
                            <div class="caption">
                                <h4 class="pull-right">$94.99</h4>
                                <h4><a href="#">Fifth Product</a>
                                </h4>
                                <p>This is a short description. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                            </div>
                            <div class="ratings">
                                <p class="pull-right">18 reviews</p>
                                <p>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star-empty"></span>
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <h4><a href="#">Like this template?</a>
                        </h4>
                        <p>If you like this template, then check out <a target="_blank" href="http://maxoffsky.com/code-blog/laravel-shop-tutorial-1-building-a-review-system/">this tutorial</a> on how to build a working review system for your online store!</p>
                        <a class="btn btn-primary" target="_blank" href="http://maxoffsky.com/code-blog/laravel-shop-tutorial-1-building-a-review-system/">View Tutorial</a>
                    </div>

                </div>

            </div>

        </div>

    </div>